stages:
  - test
before_script:
    - pwd
    - whoami
    - export PYTHONPATH="${PYTHONPATH}:/home/gitlab-runner/builds/da0b8d35/0/PUM-Company3/Software/"
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate
    - python --version
    - python ./Product/Database/DBConn.py
    - python ./Product/Database/DBFillSmallSet.py
    - python ./Product/TrendManager/RunTrend.py
    
    
test_script:
  script:
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate

    - ./test_script
  stage: test
 
 