stages:
  - test
  
before_script:
    - pwd
    - export PYTHONPATH="${PYTHONPATH}:/home/gitlab-runner/builds/6b21c71b/0/PUM-Company3/Software/Product"
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate
    - python /home/sebbe953/testvenv.py
    - python --version
    - python ./Product/Database/DBConn.py
    - python ./Product/Database/DbFillMovieLens/DBFillMovieLens.py
test_script:
  script:
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate

    - ./test_script
  stage: test
  