stages:
  - build
  - test
  
before_script:
    - pwd
    - export PYTHONPATH="${PYTHONPATH}:/home/gitlab-runner/builds/6b21c71b/0/PUM-Company3/Software/Product"
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate
    - python /home/sebbe953/testvenv.py
    - python --version


build_script:
  Script:
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate
    - python ./Product/Database/DBConn.py
    - python ./Product/Database/DbFillMovieLensGitLab/DBFillMovieLens.py
  Stage: build

test_script:
  script:
    - source /home/sebbe953/virtualenvs/pum-venv/bin/activate

    - ./test_script
  stage: test
  