version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: django
    command: bash Docker/django_docker_startup_command.sh
    depends_on:
      - website_db
      - data_db
    expose:
      - "8000"
    environment:
      - DOCKER=1
      - PRODUCTION_DATABASE=1
      - DATA_DATABASE_HOST=data_db
      - WEBSITE_DATABASE_HOST=website_db
      - ZENTERIO_PWD=${ZENTERIO_PWD}

  website_db:
    image: postgres:latest
    container_name: postgres

  data_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=main

  trending:
    build: .
    container_name: trend
    command: bash Docker/trending_startup_script.sh
    depends_on:
     - data_db
    dns: 8.8.8.8
    environment:
     - PRODUCTION_DATABASE=1
     - DATA_DATABASE_HOST=data_db
     - TWITTERSTREAM=${TWITTERSTREAM}
     - REMOVETWITTERFILES=${REMOVETWITTERFILES}

  recommendation:
    build: .
    container_name: recommendation
    command: bash Product/Docker/recommendation_startup_script.sh
    depends_on:
     - data_db
     - trending
    environment:
     - PRODUCTION_DATABASE=1
     - DATA_DATABASE_HOST=data_db
