version: '2'

services:

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./nginx/django.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn project_config.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./APIManager:/src
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
