version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: django
    command: bash django_docker_startup_command.sh
    depends_on:
      - website_db
      - data_db
    volumes:
      - .:/src
    expose:
      - "8000"
    environment:
      PRODUCTION_DATABASE: 1
      DATA_DATABASE_HOST: "data_db"
      WEBSITE_DATABASE_HOST: "website_db"

  website_db:
    image: postgres:latest
    container_name: postgres

  data_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: main
