version: '3'
services:
  frontend_db:
    image: postgres

  trending_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    build: .
    command: bash -c "cd APIManager && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/src
    ports:
      - "8000:8000"
    depends_on:
      - frontend_db
      - trending_db
    environment:
      - PYTHONUNBUFFERED=1
