version: '3'
services:
  db:
    image: postgres

  web:
    build: .
#    command: bash -c "python"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
